---
title: "Week 3 Discussion File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Part A: Make edits (no conflict)

```{r partner_1a}
# Partner 1: 
# Run the code below to see the original graph
# Change the code below to make the point color change based on 'cut', and update the theme to theme_bw(). Update the title to include your first name. 

ggplot(data = diamonds, aes(x = carat, y = price, color = cut)) +
  geom_point() +
  theme_bw() +
  labs(title = "Kirsten was here")
```

```{r partner_2a}
# Partner 2: 
# Run the code below to see the original graph
# Change the code below to make the geom a geom_jitter, and update the theme to theme_light. Update the title to include your first name. 

ggplot(data = diamonds, aes(x = color, y = carat) +
  geom_jitter() +
  theme_light() +
  labs(title = "Teague was here"))


```

## PART B: Make problems

```{r break-it-1}

ggplot(data = diamonds, aes(x = depth, y = cut)) +
  geom_point() +
  theme_minimal()
#random comment fjklasdjfkl;sajfklasjlk;fsakjsahgioewrnalsnfklasdjfkl;as dfsa   hi kirsten!

#Making a subplot
really_big_diamonds <- diamonds %>% 
  filter(carat > 3)

ggplot(data = really_big_diamonds, aes(x = carat, y = price)) +
  geom_point() +
  theme_dark()
```

```{r break-it-2}
#i have class in like 5 minutes LOL 

#boodsalkfjlkasjdklf;ajsiofealk;sdjfklasdfasd
```

## END Discussion 3
